ALTER TABLE public.hook_analyses
  ADD COLUMN IF NOT EXISTS hook_score integer,
  ADD COLUMN IF NOT EXISTS attention_trigger text,
  ADD COLUMN IF NOT EXISTS hook_structure_0_1s text,
  ADD COLUMN IF NOT EXISTS hook_structure_1_3s text,
  ADD COLUMN IF NOT EXISTS hook_structure_3_5s text,
  ADD COLUMN IF NOT EXISTS spoken_hook text,
  ADD COLUMN IF NOT EXISTS visual_hook text,
  ADD COLUMN IF NOT EXISTS onscreen_hook text,
  ADD COLUMN IF NOT EXISTS curiosity_gap text,
  ADD COLUMN IF NOT EXISTS value_promise text,
  ADD COLUMN IF NOT EXISTS pattern_interrupt text,
  ADD COLUMN IF NOT EXISTS clarity_score integer,
  ADD COLUMN IF NOT EXISTS pacing_score integer,
  ADD COLUMN IF NOT EXISTS audio_visual_match text,
  ADD COLUMN IF NOT EXISTS target_audience_signal text,
  ADD COLUMN IF NOT EXISTS commercial_intent text,
  ADD COLUMN IF NOT EXISTS cta_readiness text,
  ADD COLUMN IF NOT EXISTS retention_risk text,
  ADD COLUMN IF NOT EXISTS best_moment text,
  ADD COLUMN IF NOT EXISTS weakest_moment text,
  ADD COLUMN IF NOT EXISTS replicate_this text,
  ADD COLUMN IF NOT EXISTS avoid_this text,
  ADD COLUMN IF NOT EXISTS verdict text,
  ADD COLUMN IF NOT EXISTS three_rewrites jsonb NOT NULL DEFAULT '[]'::jsonb;